/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include<stdio.h>

typedef struct{
	volatile uint32_t RCC_CR;
	volatile uint32_t RCC_PLLCFGR;
	volatile uint32_t RCC_CFGR;
	volatile uint32_t RCC_CIR;
	volatile uint32_t RCC_AHB1RSTR;
	volatile uint32_t RCC_AHB2RSTR;
	uint32_t reserved0[2];
	volatile uint32_t RCC_APB1RSTR;
	volatile uint32_t RCC_APB2RSTR;
	uint32_t reserved1[2];
	volatile uint32_t RCC_AHB1ENR;
	volatile uint32_t RCC_AHB2ENR;
	uint32_t reserved2[2];
	volatile uint32_t RCC_APB1ENR;
	volatile uint32_t RCC_APB2ENR;

}RCC_REG;//STRUCT for RCC register mapping

typedef struct{
	volatile uint32_t GPIO_MODER;
	volatile uint32_t GPIO_OTYPER;
	volatile uint32_t GPIO_OSPEEDR;
	volatile uint32_t GPIO_PUPDR;
	volatile uint32_t GPIO_IDR;
	volatile uint32_t GPIO_ODR;
	volatile uint32_t GPIO_BSRR;
	volatile uint32_t GPIO_LCKR;
	volatile uint32_t GPIO_AFRL;
	volatile uint32_t GPIO_AFRH;
}GPIO_REG;//STRUCT for GPIO register mapping

typedef struct {
	volatile uint32_t SYSCFG_MEMRMP;
	volatile uint32_t SYSCFG_PMC;
	volatile uint32_t SYSCFG_EXTICR1;
	volatile uint32_t SYSCFG_EXTICR2;
	volatile uint32_t SYSCFG_EXTICR3;
	volatile uint32_t SYSCFG_EXTICR4;
}SYSCFG_REG;//STRUCT for System configuration register

typedef struct {
	volatile uint32_t EXTI_IMR;
	volatile uint32_t EXTI_EMR;
	volatile uint32_t EXTI_RTSR;
	volatile uint32_t EXTI_FTSR;
	volatile uint32_t EXTI_SWIER;
	volatile uint32_t EXTI_PR;
}EXTI_REG;//STRUCT for external interrupt control register

typedef struct {
	volatile uint32_t CR1;
	volatile uint32_t CR2;
	volatile uint32_t SMCR;
	volatile uint32_t SR;
	volatile uint32_t EGR;
	volatile uint32_t CCMR1;
	volatile uint32_t CCMR2;
	volatile uint32_t CCER;
	volatile uint32_t CNT;
	volatile uint32_t PSC;
	volatile uint32_t ARR;
	volatile uint32_t reserverd0[1];
	volatile uint32_t CCR[4];

}TIM_REG;

typedef struct{
	volatile uint32_t SR;
	volatile uint32_t DR;
	volatile uint32_t BRR;
	volatile uint32_t CR1;
	volatile uint32_t CR2;
	volatile uint32_t CR3;
	volatile uint32_t GTPR;
}USART_REG;

//defining the base address as a pointer to structure
#define RCC          ((RCC_REG*) 0x40023800)
#define GPIOA        ((GPIO_REG*)0x40020000)
#define GPIOC        ((GPIO_REG*)0x40020800)
#define TIM2         ((TIM_REG*)0x40000000)
#define TIM3         ((TIM_REG*)0x40000400)
#define USART1       ((USART_REG*)0x40011000)


void delay_ms(uint32_t t){
	RCC->RCC_APB1ENR|=(1<<0);//using TIM2 so first we have to enable the clock for it
	TIM2->PSC=16000-1;//1000 ticks per second(1 tick per ms). PRESCALER is the value with which we divide our internal clock frequency to reduce its speed
	TIM2->ARR=t-1;//here t is the time of delay we want
	TIM2->CNT=0;//setting count to 0;
	TIM2->EGR|=(1<<0);//setting the update generation(UG) flag so ARR and PSC get reloaded instantly(force update)
	TIM2->SR&= ~(1<<0);//clearing the status register update interrupt flag
	TIM2->CR1|=(1<<0);//start the counting by setting CEN bit
	while((TIM2->SR&(1<<0)));//run loop until hardware sets the UIF bit of status register
	TIM2->CR1&=~(1<<0);//stopping the counting
	TIM2->SR&=~(1<<0);//clearing the UIF bit for next timer
}

void delay_microsec(uint32_t t){
	RCC->RCC_APB1ENR|=(1<<0);//using TIM2 so first we have to enable the clock for it
	TIM2->PSC=16-1;//1000000 ticks per second(1 tick per us). PRESCALER is the value with which we divide our internal clock frequency to reduce its speed
	TIM2->ARR=t-1;//here t is the time of delay we want
	TIM2->CNT=0;//setting count to 0;
	TIM2->EGR|=(1<<0);//setting the update generation(UG) flag so ARR and PSC get reloaded instantly(force update)
	TIM2->SR&= ~(1<<0);//clearing the status register update interrupt flag
	TIM2->CR1|=(1<<0);//start the counting by setting CEN bit
	while((TIM2->SR&(1<<0)));//run loop until hardware sets the UIF bit of status register
	TIM2->CR1&=~(1<<0);//stopping the counting
	TIM2->SR&=~(1<<0);//clearing the UIF bit for next timer
}


void UART_WRITE(char ch){
	while(!((USART1->SR)&(1<<7))){

	}//wait till the TXE pin is low
		GPIOC->GPIO_ODR&=~(1<<13);
		 for(int i=0; i<100000; i++);
		USART1->DR=ch;//write after txe is turned high
		GPIOC->GPIO_ODR|=(1<<13);
		 for(int i=0; i<100000; i++);
}
void print(char* str){
	int i=0;
	while(str[i]){
		UART_WRITE(str[i++]);
	}
}
//main start
int main(void) {
    //set up for GPIO
    RCC->RCC_AHB1ENR|=(1<<0)|(1<<2);//enabling clock for portA
    RCC->RCC_APB2ENR|=(1<<4);//enabling clock for uart1
    RCC->RCC_APB1ENR|=(3<<1);//enabling clock for Tim2 and TIM3
    GPIOC->GPIO_MODER&=~(3<<26);//led for checking the serial data is transfered or not
    GPIOC->GPIO_MODER|=(1<<26);
    GPIOA->GPIO_MODER&=~(3<<12);
    GPIOA->GPIO_MODER|=(1<<13);//setting pin PA6 as alternate function mode
    GPIOA->GPIO_AFRL&=0xF0FFFFFF;
    GPIOA->GPIO_AFRL|=(2<<24);
    TIM3->PSC=83;//1000000 ticks per second
    TIM3->ARR=999;//1000 ticks per ms
    TIM3->CNT=0;
    TIM3->CCMR1&=~(7<<4);//clearing the pwm mode bits
    TIM3->CCMR1|=(3<<5);//setting pwm mode 1
    TIM3->CCMR1|=(1<<3);//etting channel 1 preload bit
    TIM3->CCER|=(1<<0);//enabling the channel 1
    TIM3->CR1|=(1<<0);//starting the count by setting count enable bit
    TIM3->CCR[0]=250;//setting duty cuycle(25%)

    GPIOA->GPIO_MODER&=~(3<<18);//setting UART! pin PA9 and PA10 as alternate function
    GPIOA->GPIO_MODER|=(2<<18);
    GPIOA->GPIO_AFRH&=~(15<<4);//claring the line 9 of Alternate function high(line 8-15)register
    GPIOA->GPIO_AFRH|=(7<<4);//setting value 7 as UART1 AFR maps to UART1 with value AF7;
    USART1->BRR=0x8B;
    USART1->CR1|=(1<<13)|(1<<3)|(1<<2);//setting UE, TE, RE bit

    //infinite loop
    while(1) {
    	//in order to get half seconds delay we will pass 250 (as 500 ticks in 1 seconds so 250 tick in half seconds)
    	char buffer[50];
//    	int mean_volt=(float)TIM3->CCR[0]/(TIM3->ARR+1)*3.3;
    	sprintf(buffer,"The Intensity of led is %lu",TIM3->CCR[0]/1000);
    	print(buffer);
   	 for(int i=0; i<3000000; i++);
//    	delay_ms(500);//500 ms delay
     //lets suppose CPU is executing its task in loop
    }
}




