/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

//Rcc base register address
#define RCC_BASE      0x40023800
//address of general purpose clock enabling
#define RCC_AHB1ENR   (*(volatile uint32_t *)(RCC_BASE + 0x30))
//gpio port c base address
#define GPIOC_BASE    0x40020800
//moder register address to set the pin as input or output
#define GPIOC_MODER   (*(volatile uint32_t *)(GPIOC_BASE + 0x00))
//output data register to write to the port pin
#define GPIOC_ODR     (*(volatile uint32_t *)(GPIOC_BASE + 0x14))
//main start
int main(void) {
    // first enable the clock for port c (to wake the controller)
    RCC_AHB1ENR |= (1 << 2);
//to set the port c pin 13 as ouput we need to write 01 to bit 27&26 as each pin takes two bit
    GPIOC_MODER &= ~(3 << 26); // first clear the bit 26 and 27
    GPIOC_MODER |=  (1 << 26); // Setting bit 26 and 27 to 10
    //infinite loop
    while(1) {
        //toggle the led state using xor operator
    	//if led state is 1 xor will nake it 0 and if state is zero xor will make it 1
        GPIOC_ODR ^= (1 << 13);
        //Simple delay loop
        for(int i = 0; i < 500000; i++);
    }
}

